def COLOR_MAP = [
    'SUCCESS': 'good',
    'ABORTED': 'warning',
    'FAILURE': 'danger'
]


node {  
        stage('Parameters Setup'){
                properties([
                    parameters([
                        booleanParam(
                            defaultValue: false, 
                            description: '', 
                            name: 'DeleteStack'
                        ),
                        string(
                            defaultValue: 'DanishTestStack2', 
                            name: 'StackName', 
                            trim: true
                        ),
                        string(
                            name: 'StackS3BucketName',
                            defaultValue: "danishbucket"
                        )
                        
                    ])
                ])
        }
        if ( ! params.DeleteStack ){
        stage('Create') {
            sh '''#!/bin/bash
                    aws cloudformation describe-stacks --region 'us-west-2' --stack-name ${StackName} &> /dev/null
                    status=$?
                    if [[ status -ne 0 ]] ; then 
                    aws cloudformation create-stack --stack-name ${StackName} --template-url https://danishbucket458.s3.us-west-2.amazonaws.com/s3cft.yml --region 'us-west-2' --parameters ParameterKey=BucketName,ParameterValue=${StackS3BucketName} ;
                    aws cloudformation wait stack-create-complete --region 'us-west-2' --stack-name  ${StackName};
                    echo "Created" ; fi
            '''
        }
        stage('Update') {
            sh '''#!/bin/bash
                    aws cloudformation describe-stacks --region 'us-west-2' --stack-name ${StackName} &> /dev/null
                    status=$?
                    if [[ status -eq 0 ]] ; then
                    aws cloudformation update-stack --stack-name ${StackName} --template-url https://danishbucket458.s3.us-west-2.amazonaws.com/s3cft.yml --region 'us-west-2' --parameters ParameterKey=BucketName,ParameterValue=${StackS3BucketName} 2> /dev/null;
                    #sleep 30
                    echo "Updated" ; fi
            '''
        }}
        else{
        stage('Delete') {
            sh '''#!/bin/bash
                    aws cloudformation delete-stack --stack-name ${StackName} --region 'us-west-2'; 
                    echo "Deleted" ;
            '''
        } }


            slackSend channel: 'danishjenkinstest',
                    color: COLOR_MAP[currentBuild.currentResult],
                    message: "Status : *${currentBuild.currentResult}:* \n Job name: ${env.JOB_NAME} build no. : ${env.BUILD_NUMBER} \n\n For more Information: ${env.BUILD_URL}"
 
}
