pipeline {
    agent any
    stages {
        stage('cloudformation') {
            steps {
                sh '''
                    #!/bin/bash
                    { aws cloudformation describe-stacks --region 'us-west-2' --stack-name params.StackName; } 2> /dev/null
                    status=$?
                    if [[ status -ne 0 ]] ; then 
                    aws cloudformation create-stack --stack-name ${params.StackName} --template-url https://danishbucket458.s3.us-west-2.amazonaws.com/s3cft.yml --region 'us-west-2';
                    aws cloudformation wait stack-create-complete --region 'us-west-2' --stack-name  ${params.StackName};
                    elif [ status == 0 ] && [ ${params.DeleteStack} == "false" ] ; then
                    aws cloudformation update-stack --stack-name ${params.StackName} --template-url https://danishbucket458.s3.us-west-2.amazonaws.com/s3cft.yml --region 'us-west-2';
                    aws cloudformatio wait stack-update-complete --region 'us-west-2' --stack-name  ${params.StackName};
                    else
                    aws cloudformation delete-stack --stack-name ${params.StackName} --region 'us-west-2'; fi
                '''
              }
             }
            }
            }
