pipeline {
    agent any
    stages {
        stage('Setup parameters') {
            steps {
                script { 
                    properties([
                        parameters([
                            booleanParam(
                                defaultValue: false, 
                                description: '', 
                                name: 'DeleteStack'
                            ),
                            string(
                                defaultValue: 'DanishTestStack', 
                                name: 'StackName', 
                                trim: true
                            )
                        ])
                    ])
                }
            }
        }        
        stage('cloudformation') {
            steps {
                sh '''#!/bin/bash
                        echo ${param.DanishTestStack}
                '''
              }
             }
            }
        }
